### ISSUE TITLE
On scrolling i am getting "specified child already has a parent. You must call removeView() on the child's parent first"

### ISSUE THREAD

**Issue by sayagodshala** [demoNo/AutoScrollViewPager#9]
2019-06-13 18:13:33.275 7104-7104/com.vlv.aravali.preprod E/MessageQueue-JNI: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:4583)
        at android.view.ViewGroup.addView(ViewGroup.java:4424)
        at androidx.viewpager.widget.ViewPager.addView(ViewPager.java:1485)
        at android.view.ViewGroup.addView(ViewGroup.java:4364)
        at android.view.ViewGroup.addView(ViewGroup.java:4337)
        at com.vlv.aravali.views.widgets.scroller.v1.RecyclingPagerAdapter.instantiateItem(RecyclingPagerAdapter.java:34)
        at androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1224)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager$3.run(ViewPager.java:273)
        at androidx.viewpager.widget.ViewPager.completeScroll(ViewPager.java:2005)
        at androidx.viewpager.widget.ViewPager.onInterceptTouchEvent(ViewPager.java:2135)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2247)

**Comment by demoNo** [comment]
did you use adapter extends `InfinitePagerAdapter`?, what is `com.vlv.aravali.views.widgets.scroller.v1.RecyclingPagerAdapter`, if it's your own PagerAdapter, you should make it extends `InfinitePagerAdapter`.

```java
public class MyAdapter extends InfinitePagerAdapter {

    private List<String> data;

    public MyAdapter(List<String> data) {
        this.data = data;
    }

    @Override
    public int getItemCount() {
        return data == null ? 0 : data.size();
    }

    @Override
    public View getItemView(int position, View convertView, ViewGroup container) {
        return your view;
    }
}
```

**Comment by wziwen** [comment]
I have the same problem. turns out that it's my mistake.
the getItemView() is chagned from normal ViewPagerAdapter, so i call 'container.addView()', that is what goes wrong.
```
    @Override
    public View getItemView(int position, View convertView, ViewGroup container) {
        if (convertView != null) {
            return convertView;
        }
        AdEntity resumeAdEntity = datas.get(position);
        View view = LayoutInflater.from(container.getContext()).inflate(R.layout.view_resume_ad, null);
        ImageView imageView = view.findViewById(R.id.iv_img);
        Glide.with(imageView.getContext())
                .load(resumeAdEntity.getUrl())
                .into(imageView);
        view.setTag(resumeAdEntity);
//        container.addView(view);  //error here
        return view;
    }
```

**Comment by demoNo** [comment]
@wziwen you should do like this
```java
if (convertView == null) {
                convertView = new TextView(container.getContext());
                ((TextView) convertView).setGravity(Gravity.CENTER);
                ((TextView) convertView).setTextSize(TypedValue.COMPLEX_UNIT_SP, 60);
                ((TextView) convertView).setTypeface(null, Typeface.BOLD);
                ((TextView) convertView).setTextColor(Color.parseColor("#ffffff"));
                convertView.setLayoutParams(layoutParams);
            }
      ((TextView) convertView).setText(position + "");
      return convertView;
```
